// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgtefausurnggfmijynu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZndGVmYXVzdXJuZ2dmbWlqeW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTQ5NDUsImV4cCI6MjA3MDEzMDk0NX0.aGT5dQxllHBdXhk-K7dYJksmhi-3OLHSbKhIE6HbiR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});